### ISSUE TITLE
Rahiph Mokuro - Nível 3: **Arma energética**

### ISSUE THREAD

**Issue by dinhoaps** [jenipappo/yu-yu-hakusho-rpg#3]
Como um NPC, um dos reis das trevas tem o mesmo dano e custo de sua habilidade nível 3 que a disciplina nível 3 de Suzuki????

**Comment by Noeh83** [comment]
É um pouco mais forte, mas ele já ganha muito bônus de dano. Tem que ver todos os níveis juntos. E não só analisar um por um.
